### PR TITLE
Add seed to the random choice

### PR DESCRIPTION
**Pull request by scrummyin**
This allows for the ability to use a seed for the random number
generator. This means that a seed value can be used to get a
deterministic HRID, by using the same seed as previous on any
consecutive runs.

An example of the run is below
```
>>> import hrid
>>> hrid.hrid.HRID(seed='seed').generate() == hrid.hrid.HRID(seed='seed').generate()
True
>>> hrid.hrid.HRID(seed='seed').generate() == hrid.hrid.HRID(seed='seedsssssssss').generate()
False
>>> hrid.hrid.HRID(seed='seed').generate() == hrid.hrid.HRID(seed='seed').generate()
True
```

### CODE REVIEW

**Review by pierec — APPROVED** [review]
LGTM! Some tests would be in order.

**Comment by pierec** [comment]
@hnimminh is there any interest in merging this PR and releasing a new version of the package?

**Comment by hnimminh** [comment]
@pierec  Somehow I missed this for longtime. I will update soon.
@scrummyin thanks for your contribution

**Comment by hnimminh** [comment]
@pierec https://pypi.org/project/hrid/ 0.2.4 ^^

**Pull request merged**
